import Anthropic from "@anthropic-ai/sdk";
import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";

export async function POST(req: NextRequest) {
  // Auth check
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { imageUrl } = await req.json();

  if (!imageUrl) {
    return NextResponse.json(
      { error: "No image URL provided" },
      { status: 400 }
    );
  }

  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    return NextResponse.json(
      {
        error:
          "AI analysis is not configured. Please add ANTHROPIC_API_KEY to your environment variables.",
      },
      { status: 503 }
    );
  }

  try {
    // Fetch the image and convert to base64
    const imgRes = await fetch(imageUrl);
    if (!imgRes.ok) {
      throw new Error("Failed to fetch image");
    }

    const buffer = await imgRes.arrayBuffer();
    const base64 = Buffer.from(buffer).toString("base64");
    const contentType = imgRes.headers.get("content-type") || "image/jpeg";

    // Validate media type for Anthropic API
    const validTypes = [
      "image/jpeg",
      "image/png",
      "image/gif",
      "image/webp",
    ] as const;
    type ValidMediaType = (typeof validTypes)[number];
    const mediaType: ValidMediaType = validTypes.includes(
      contentType as ValidMediaType
    )
      ? (contentType as ValidMediaType)
      : "image/jpeg";

    const client = new Anthropic({ apiKey });

    const message = await client.messages.create({
      model: "claude-sonnet-4-5-20250929",
      max_tokens: 2048,
      messages: [
        {
          role: "user",
          content: [
            {
              type: "image",
              source: {
                type: "base64",
                media_type: mediaType,
                data: base64,
              },
            },
            {
              type: "text",
              text: `You are a medical imaging AI assistant. Analyze this medical image and provide a structured assessment:

1. **Modality**: Identify the imaging modality (X-ray, CT, MRI, Ultrasound, etc.)
2. **Anatomical Region**: Identify the body region and view/projection
3. **Technical Quality**: Brief assessment of image quality, positioning, and exposure
4. **Key Observations**: List notable anatomical structures and any visible findings
5. **Summary**: A brief summary paragraph

IMPORTANT DISCLAIMER: This analysis is generated by AI for educational and reference purposes only. It does NOT constitute a medical diagnosis. Always rely on qualified radiologists and clinicians for definitive interpretation. AI analysis should be used as a supplementary tool, not a replacement for professional medical judgment.

Keep the response concise and well-structured with the headers above.`,
            },
          ],
        },
      ],
    });

    const analysisText =
      message.content[0].type === "text" ? message.content[0].text : "";

    return NextResponse.json({ analysis: analysisText });
  } catch (err: unknown) {
    console.error("AI analysis error:", err);
    const errorMessage =
      err instanceof Error ? err.message : "Analysis failed";
    return NextResponse.json({ error: errorMessage }, { status: 500 });
  }
}
